### ISSUE TITLE
Update dependencies to prepare for Scala Steward

### ISSUE THREAD

**Issue by RomanLebid** [sky-uk/kafka-topic-loader#49]
Currently more and more teams now have Scala Steward enabled for their repos. Unfortunately, that combination can sometimes prevent engineers from upgrading, as some library maintainers don't pay enough attention to binary compatibility.

That situation can be improved now that [eviction warnings have become eviction errors](https://www.scala-lang.org/blog/2021/02/16/preventing-version-conflicts-with-versionscheme.html) and it's much easier to find out about any possible issues at compile time.

Proposed solution is to enable scala-steward for kafka-topic-loader repository, so that teams can all align on the same versions of these dependencies by keeping them up to date.

kafka-topic-loader has quite a few libraries in use, so to avoid a deluge of PRs coming in all at once, it would be easier to update most of them:
* `refined` and `pureconfig` as they are the most notorious to break binary compatibility
* `akka` [does not allow mixed versioning](https://doc.akka.io/docs/akka/current/common/binary-compatibility-rules.html#mixed-versioning-is-not-allowed) and you need to explicitly provide all your deps with with the version in use
```
java.lang.IllegalStateException: You are using version 2.6.15 of Akka, but it appears you (perhaps indirectly) 
also depend on older versions of related artifacts. You can solve this by adding an explicit dependency 
on version 2.6.15 of the [akka-discovery] artifacts to your project.
```

**Comment by paulaylingdev** [comment]
Scala steward has been added, dependencies are now being updated.

The following seem to satisfy this issue:
- #50 
- #51
